apiVersion: apps/v1
kind: Deployment
metadata:
  name: config 
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      app: config 
  template:
    metadata:
      labels:
        app: config 
    spec:
      containers:
      - name: config 
        image: "nickdsnyder/config:{{ .Chart.Version }}"
        env:
        - name: CONFIG_PORT
          value: "{{ .Values.config.internalPort }}"
        ports:
        - containerPort: {{ .Values.config.internalPort }} 
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.config.internalPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.config.internalPort }}