apiVersion: apps/v1
kind: Deployment
metadata:
  name: config 
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      name: config 
  template:
    metadata:
      labels:
        name: config 
    spec:
      containers:
      - name: config 
        image: "nickdsnyder/config:{{ .Chart.Version }}"
        env:
        - name: CONFIG_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080