kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.serviceType }} 
  selector:
    name: frontend 
  ports:
  - protocol: TCP 
    port: 80
    nodePort: 30080
    targetPort: http