apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config
  template:
    metadata:
      labels:
        name: config
    spec:
      volumes:
        - name: config-persistent-volume
          persistentVolumeClaim:
            claimName: config-persistent-volume-claim
        - configMap:
            defaultMode: 464
            name: config-map
          name: config-map
      containers:
        - name: config
          image: "nickdsnyder/config:v1.0.0"
          env:
            - name: CONFIG_PORT
              value: "8080"
            - name: CONFIG_PATH
              value: "/config"
            - name: CONFIG_MAP
              value: "/config-map/config.json"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: "/config"
              name: config-persistent-volume
            - mountPath: /config-map
              name: config-map
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
