kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-persistent-volume-claim
spec:
  # storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi