kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    app: hello-server
spec:
  type: NodePort
  selector:
    name: frontend 
  ports:
  - protocol: TCP 
    port: 80
    nodePort: 30080
    targetPort: http