kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-0
  labels:
    app: hello-server
spec:
  # storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
