apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-0
  labels:
    app: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-0
  template:
    metadata:
      labels:
        name: config-0
    spec:
      volumes:
      - name: config-persistent-volume-0
        persistentVolumeClaim:
          claimName: config-0
      containers:
      - name: config-0
        image: "nickdsnyder/config:v1.0.0"
        env:
        - name: CONFIG_PORT
          value: "8080"
        - name: CONFIG_PATH
          value: "/config"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
          - mountPath: "/config"
            name: config-persistent-volume-0
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
